### ISSUE TITLE
pcm文件怎么传入呢

### ISSUE THREAD

**Issue by Toxic12138** [chenjiale/js-webapi#1]
请问pcm文件怎么处理传入呢

**Comment by chenjiale** [comment]
不知道你的文件是怎么来的，h5是不能直接读本地文件的。
1、除非用的文件选择框先选择本地文件，然后获取input元素的input.files[0]对象就是blob对象了。
2、将文件base64编码，然后用js转换成blob对象应该也可以的

**Comment by Toxic12138** [comment]
> 不知道你的文件是怎么来的，h5是不能直接读本地文件的。
> 1、除非用的文件选择框先选择本地文件，然后获取input元素的input.files[0]对象就是blob对象了。
> 2、将文件base64编码，然后用js转换成blob对象应该也可以的

谢谢你，确实可以
